import express from 'express';
import { userAuthMiddleware } from '../middlewares/auth-middleware.js';
import UserController from '../../controllers/user-controller.js';

const router = express.Router();
const userController = new UserController();

router.post(
  '/',
  /*
    #swagger.summary = 'Create a user'
    #swagger.description = 'Create a new user'
    #swagger.requestBody = {
      required: true,
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/NewUser' }
        }
      }
    }
    #swagger.responses[201] = {
      description: 'User created successfully - No content'
    }
    #swagger.responses[400] = {
      description: 'Bad Request - Invalid input data',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: {
              summary: 'An example of invalid values',
              value: {
                message: 'Validation error.',
                errors: ['Validation validationName on fieldName failed']
              }
            }
          }
        }
      }
    }
    #swagger.responses[409] = {
      description: 'Conflict - User cannot be created',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: {
              summary: 'An example of an existing username',
              value: {
                message: 'Unique constraint error.',
                errors: [ 'Value already exists for user_username' ]
              }
            },
            e2: {
              summary: 'An example of an existing email',
              value: {
                message: 'Unique constraint error.',
                errors: [ 'Value already exists for user_email' ]
              }
            }
          }
        }
      }
    }
    #swagger.responses[500] = {
      description: 'Internal Server Error',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: {
              summary: 'An example of a key gen failure',
              value: {
                message: 'Failed to generate RSA keys.',
                errors: []
              }
            },
            e1: {
              summary: 'An example of a transaction error',
              value: {
                message: 'Failed to create user account.',
                errors: []
              }
            }
          }
        }
      }
    }
  */
  userController.createUser
);
router.get(
  '/:id/confirm',
  /*
    #swagger.summary = 'Activate user account'
    #swagger.description = 'Activate a new user account'
    #swagger.parameters['token'] = {
      in: 'query',
      description: 'JWT generated by the server on user creation',
      required: true,
      schema: { type: 'string' }
    }
    #swagger.responses[204] = {
      description: 'Account activated successfully - No content'
    }
    #swagger.responses[400] = {
      description: 'Bad Request - Invalid input data',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: {
              summary: 'An example of an expired token',
              value: {
                message: 'Token is expired.',
                errors: []
              }
            },
            e2: {
              summary: 'An example of an invalid token payload',
              value: {
                message: 'Token is invalid.',
                errors: []
              }
            },
            e3: {
              summary: 'An example of an invalid user id',
              value: {
                message: 'User account is not pending.',
                errors: []
              }
            }
          }
        }
      }
    }
    #swagger.responses[500] = {
      description: 'Internal Server Error',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: {
              summary: 'An example of token verification failure',
              value: {
                message: 'Failed to verify email confirmation token.',
                errors: []
              }
            }
          }
        }
      }
    }
  */
  userController.activateAccount
);
router.post(
  '/login',
  /*
    #swagger.summary = 'User login'
    #swagger.description = 'User login'
    #swagger.requestBody = {
      required: true,
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/IdentifierLogin' }
        }
      }
    }
    #swagger.responses[200] = {
      description: 'User logged in successfully',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Token' }
        }
      }
    }
    #swagger.responses[401] = {
      description: 'Unauthorized - Invalid credentials',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: {
              summary: 'An example of an unauthorized error',
              value: {
                message: 'Invalid credentials.',
                errors: ['Password does not match']
              }
            }
          }
        }
      }
    }
    #swagger.responses[404] = {
      description: 'Not found - User does not exist',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: {
              summary: 'An example of an not found error',
              value: {
                message: 'User does not exist.',
                errors: []
              }
            }
          }
        }
      }
    }
    #swagger.responses[500] = {
      description: 'Internal Server Error',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: {
              summary: 'An example of a not matching password',
              value: {
                message: 'Failed to compare passwords on login.',
                errors: []
              }
            },
            e1: {
              summary: 'An example of a token verification error',
              value: {
                message: 'Failed to sign login token.',
                errors: ['Some message']
              }
            }
          }
        }
      }
    }
  */
  userController.login
);

export default router;
