import express from 'express';
import UserController from '../../controllers/user-controller.js';

const router = express.Router();
const userController = new UserController();

router.post(
  '/',
  /*
    #swagger.summary = 'Create a user'
    #swagger.description = 'Create a new user'
    #swagger.requestBody = {
      required: true,
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/NewUser' }
        }
      }
    }
    #swagger.responses[201] = {
      description: 'User created successfully - No content'
    }
    #swagger.responses[400] = {
      description: 'Bad Request - Invalid input data',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: { $ref: '#/components/examples/ValidationError' }
          }
        }
      }
    }
    #swagger.responses[409] = {
      description: 'Conflict - User cannot be created',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: { $ref: '#/components/examples/ConflictingUsername' },
            e2: { $ref: '#/components/examples/ConflictingEmail' }
          }
        }
      }
    }
    #swagger.responses[500] = {
      description: 'Internal Server Error',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: { $ref: '#/components/examples/KeyGenError' },
            e2: { $ref: '#/components/examples/TokenSignError' },
            e3: { $ref: '#/components/examples/AccountConfirmationEmailError' },
            e4: { $ref: '#/components/examples/UserCreationError' }
          }
        }
      }
    }
  */
  userController.createUser
);
router.get(
  '/:id/confirm',
  /*
    #swagger.summary = 'Activate user account'
    #swagger.description = 'Activate a new user account'
    #swagger.parameters['token'] = {
      in: 'query',
      description: 'JWT generated by the server on user creation',
      required: true,
      schema: { type: 'string' }
    }
    #swagger.responses[204] = {
      description: 'Account activated successfully - No content'
    }
    #swagger.responses[400] = {
      description: 'Bad Request - Invalid input data',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: { $ref: '#/components/examples/ExpiredToken' },
            e2: { $ref: '#/components/examples/InvalidTokenPayload' },
            e3: { $ref: '#/components/examples/NotPendingAccount' }
          }
        }
      }
    }
    #swagger.responses[500] = {
      description: 'Internal Server Error',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: { $ref: '#/components/examples/TokenVerifyError' }
          }
        }
      }
    }
  */
  userController.activateAccount
);
router.post(
  '/login',
  /*
    #swagger.summary = 'User login'
    #swagger.description = 'User login'
    #swagger.requestBody = {
      required: true,
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/IdentifierLogin' }
        }
      }
    }
    #swagger.responses[200] = {
      description: 'User logged in successfully',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Token' }
        }
      }
    }
    #swagger.responses[401] = {
      description: 'Unauthorized - Invalid credentials',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: { $ref: '#/components/examples/WrongPasswordError' }
          }
        }
      }
    }
    #swagger.responses[404] = {
      description: 'Not found - User does not exist',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: { $ref: '#/components/examples/UserNotFound' }
          }
        }
      }
    }
    #swagger.responses[500] = {
      description: 'Internal Server Error',
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/Error' },
          examples: {
            e1: { $ref: '#/components/examples/ComparePasswordsError' },
            e2: { $ref: '#/components/examples/TokenSignError' }
          }
        }
      }
    }
  */
  userController.login
);

export default router;
